// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package helloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _struct "github.com/golang/protobuf/ptypes/struct"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest3_Corpus int32

const (
	HelloRequest3_UNIVERSAL HelloRequest3_Corpus = 0
	HelloRequest3_WEB       HelloRequest3_Corpus = 1
	HelloRequest3_IMAGES    HelloRequest3_Corpus = 2
	HelloRequest3_LOCAL     HelloRequest3_Corpus = 3
	HelloRequest3_NEWS      HelloRequest3_Corpus = 4
	HelloRequest3_PRODUCTS  HelloRequest3_Corpus = 5
	HelloRequest3_VIDEO     HelloRequest3_Corpus = 6
)

var HelloRequest3_Corpus_name = map[int32]string{
	0: "UNIVERSAL",
	1: "WEB",
	2: "IMAGES",
	3: "LOCAL",
	4: "NEWS",
	5: "PRODUCTS",
	6: "VIDEO",
}
var HelloRequest3_Corpus_value = map[string]int32{
	"UNIVERSAL": 0,
	"WEB":       1,
	"IMAGES":    2,
	"LOCAL":     3,
	"NEWS":      4,
	"PRODUCTS":  5,
	"VIDEO":     6,
}

func (x HelloRequest3_Corpus) String() string {
	return proto.EnumName(HelloRequest3_Corpus_name, int32(x))
}
func (HelloRequest3_Corpus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_hello_da073ee0a04ef955, []int{2, 0}
}

// The request message containing the user's name.
type HelloRequest struct {
	// Types that are valid to be assigned to Avatar:
	//	*HelloRequest_Name
	//	*HelloRequest_Id
	Avatar               isHelloRequest_Avatar `protobuf_oneof:"avatar"`
	Definition           *_struct.Struct       `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	LastModified         *timestamp.Timestamp  `protobuf:"bytes,4,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_da073ee0a04ef955, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

type isHelloRequest_Avatar interface {
	isHelloRequest_Avatar()
}

type HelloRequest_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type HelloRequest_Id struct {
	Id int64 `protobuf:"varint,2,opt,name=id,proto3,oneof"`
}

func (*HelloRequest_Name) isHelloRequest_Avatar() {}

func (*HelloRequest_Id) isHelloRequest_Avatar() {}

func (m *HelloRequest) GetAvatar() isHelloRequest_Avatar {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *HelloRequest) GetName() string {
	if x, ok := m.GetAvatar().(*HelloRequest_Name); ok {
		return x.Name
	}
	return ""
}

func (m *HelloRequest) GetId() int64 {
	if x, ok := m.GetAvatar().(*HelloRequest_Id); ok {
		return x.Id
	}
	return 0
}

func (m *HelloRequest) GetDefinition() *_struct.Struct {
	if m != nil {
		return m.Definition
	}
	return nil
}

func (m *HelloRequest) GetLastModified() *timestamp.Timestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*HelloRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _HelloRequest_OneofMarshaler, _HelloRequest_OneofUnmarshaler, _HelloRequest_OneofSizer, []interface{}{
		(*HelloRequest_Name)(nil),
		(*HelloRequest_Id)(nil),
	}
}

func _HelloRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*HelloRequest)
	// avatar
	switch x := m.Avatar.(type) {
	case *HelloRequest_Name:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Name)
	case *HelloRequest_Id:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Id))
	case nil:
	default:
		return fmt.Errorf("HelloRequest.Avatar has unexpected type %T", x)
	}
	return nil
}

func _HelloRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*HelloRequest)
	switch tag {
	case 1: // avatar.name
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Avatar = &HelloRequest_Name{x}
		return true, err
	case 2: // avatar.id
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Avatar = &HelloRequest_Id{int64(x)}
		return true, err
	default:
		return false, nil
	}
}

func _HelloRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*HelloRequest)
	// avatar
	switch x := m.Avatar.(type) {
	case *HelloRequest_Name:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Name)))
		n += len(x.Name)
	case *HelloRequest_Id:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Id))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type HelloRequest2 struct {
	List                 []*HelloRequest `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HelloRequest2) Reset()         { *m = HelloRequest2{} }
func (m *HelloRequest2) String() string { return proto.CompactTextString(m) }
func (*HelloRequest2) ProtoMessage()    {}
func (*HelloRequest2) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_da073ee0a04ef955, []int{1}
}
func (m *HelloRequest2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest2.Unmarshal(m, b)
}
func (m *HelloRequest2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest2.Marshal(b, m, deterministic)
}
func (dst *HelloRequest2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest2.Merge(dst, src)
}
func (m *HelloRequest2) XXX_Size() int {
	return xxx_messageInfo_HelloRequest2.Size(m)
}
func (m *HelloRequest2) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest2.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest2 proto.InternalMessageInfo

func (m *HelloRequest2) GetList() []*HelloRequest {
	if m != nil {
		return m.List
	}
	return nil
}

type HelloRequest3 struct {
	Corpus               HelloRequest3_Corpus `protobuf:"varint,1,opt,name=corpus,proto3,enum=helloworld.HelloRequest3_Corpus" json:"corpus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HelloRequest3) Reset()         { *m = HelloRequest3{} }
func (m *HelloRequest3) String() string { return proto.CompactTextString(m) }
func (*HelloRequest3) ProtoMessage()    {}
func (*HelloRequest3) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_da073ee0a04ef955, []int{2}
}
func (m *HelloRequest3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest3.Unmarshal(m, b)
}
func (m *HelloRequest3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest3.Marshal(b, m, deterministic)
}
func (dst *HelloRequest3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest3.Merge(dst, src)
}
func (m *HelloRequest3) XXX_Size() int {
	return xxx_messageInfo_HelloRequest3.Size(m)
}
func (m *HelloRequest3) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest3.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest3 proto.InternalMessageInfo

func (m *HelloRequest3) GetCorpus() HelloRequest3_Corpus {
	if m != nil {
		return m.Corpus
	}
	return HelloRequest3_UNIVERSAL
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_da073ee0a04ef955, []int{3}
}
func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (dst *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(dst, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloRequest2)(nil), "helloworld.HelloRequest2")
	proto.RegisterType((*HelloRequest3)(nil), "helloworld.HelloRequest3")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterEnum("helloworld.HelloRequest3_Corpus", HelloRequest3_Corpus_name, HelloRequest3_Corpus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SayHello2(ctx context.Context, in *HelloRequest2, opts ...grpc.CallOption) (*HelloReply, error)
	SayHello3(ctx context.Context, in *HelloRequest3, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayHello2(ctx context.Context, in *HelloRequest2, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayHello3(ctx context.Context, in *HelloRequest3, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello3", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayHello2(context.Context, *HelloRequest2) (*HelloReply, error)
	SayHello3(context.Context, *HelloRequest3) (*HelloReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayHello2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello2(ctx, req.(*HelloRequest2))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayHello3_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest3)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello3(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello3",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello3(ctx, req.(*HelloRequest3))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "SayHello2",
			Handler:    _Greeter_SayHello2_Handler,
		},
		{
			MethodName: "SayHello3",
			Handler:    _Greeter_SayHello3_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_hello_da073ee0a04ef955) }

var fileDescriptor_hello_da073ee0a04ef955 = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xdd, 0x8e, 0xd2, 0x40,
	0x14, 0xc7, 0x19, 0xe8, 0x16, 0x38, 0x80, 0x36, 0x27, 0x46, 0x2b, 0x9a, 0xd8, 0xf4, 0xc2, 0x70,
	0x61, 0xba, 0xa6, 0xbd, 0xd0, 0x1b, 0x3f, 0x80, 0x6d, 0x16, 0x12, 0x76, 0x21, 0xd3, 0xdd, 0x25,
	0xf1, 0xc6, 0x74, 0xe9, 0x80, 0x93, 0xb4, 0x4c, 0x6d, 0x07, 0x95, 0x07, 0xf2, 0x25, 0x7c, 0x07,
	0xdf, 0xc9, 0x74, 0x80, 0x88, 0x1f, 0x4d, 0xf6, 0x6e, 0xce, 0x9c, 0xdf, 0xff, 0x7f, 0xce, 0x9c,
	0x39, 0xd0, 0xfa, 0xc4, 0xe2, 0x58, 0x38, 0x69, 0x26, 0xa4, 0x40, 0x50, 0xc1, 0x57, 0x91, 0xc5,
	0x51, 0xf7, 0xe9, 0x4a, 0x88, 0x55, 0xcc, 0x4e, 0x55, 0xe6, 0x76, 0xb3, 0x3c, 0xcd, 0x65, 0xb6,
	0x59, 0xc8, 0x1d, 0xd9, 0x7d, 0xf6, 0x77, 0x56, 0xf2, 0x84, 0xe5, 0x32, 0x4c, 0xd2, 0x1d, 0x60,
	0xff, 0x20, 0xd0, 0x1e, 0x15, 0x6e, 0x94, 0x7d, 0xde, 0xb0, 0x5c, 0xe2, 0x03, 0xd0, 0xd6, 0x61,
	0xc2, 0x4c, 0x62, 0x91, 0x5e, 0x73, 0x54, 0xa1, 0x2a, 0x42, 0x03, 0xaa, 0x3c, 0x32, 0xab, 0x16,
	0xe9, 0xd5, 0x46, 0x15, 0x5a, 0xe5, 0x11, 0xbe, 0x02, 0x88, 0xd8, 0x92, 0xaf, 0xb9, 0xe4, 0x62,
	0x6d, 0xd6, 0x2c, 0xd2, 0x6b, 0xb9, 0x8f, 0x9c, 0x5d, 0x39, 0xe7, 0x50, 0xce, 0x09, 0x54, 0x33,
	0xf4, 0x08, 0xc5, 0x77, 0xd0, 0x89, 0xc3, 0x5c, 0x7e, 0x4c, 0x44, 0xc4, 0x97, 0x9c, 0x45, 0xa6,
	0xa6, 0xb4, 0xdd, 0x7f, 0xb4, 0x57, 0x87, 0x56, 0x69, 0xbb, 0x10, 0x5c, 0xec, 0xf9, 0x41, 0x03,
	0xf4, 0xf0, 0x4b, 0x28, 0xc3, 0xcc, 0x7e, 0x03, 0x9d, 0xe3, 0xde, 0x5d, 0x7c, 0x01, 0x5a, 0xcc,
	0x73, 0x69, 0x12, 0xab, 0xd6, 0x6b, 0xb9, 0xa6, 0xf3, 0x7b, 0x4e, 0xce, 0x31, 0x48, 0x15, 0x65,
	0x7f, 0x27, 0x7f, 0xea, 0x3d, 0x7c, 0x0d, 0xfa, 0x42, 0x64, 0xe9, 0x26, 0x57, 0xcf, 0xbf, 0xe7,
	0x5a, 0x65, 0x0e, 0x9e, 0x33, 0x54, 0x1c, 0xdd, 0xf3, 0xf6, 0x07, 0xd0, 0x77, 0x37, 0xd8, 0x81,
	0xe6, 0xf5, 0xe5, 0xf8, 0xc6, 0xa7, 0x41, 0x7f, 0x62, 0x54, 0xb0, 0x0e, 0xb5, 0xb9, 0x3f, 0x30,
	0x08, 0x02, 0xe8, 0xe3, 0x8b, 0xfe, 0xb9, 0x1f, 0x18, 0x55, 0x6c, 0xc2, 0xc9, 0x64, 0x3a, 0xec,
	0x4f, 0x8c, 0x1a, 0x36, 0x40, 0xbb, 0xf4, 0xe7, 0x81, 0xa1, 0x61, 0x1b, 0x1a, 0x33, 0x3a, 0x3d,
	0xbb, 0x1e, 0x5e, 0x05, 0xc6, 0x49, 0x81, 0xdc, 0x8c, 0xcf, 0xfc, 0xa9, 0xa1, 0xdb, 0xcf, 0x01,
	0xf6, 0xb5, 0xd3, 0x78, 0x8b, 0x26, 0xd4, 0x13, 0x96, 0xe7, 0xe1, 0x6a, 0xff, 0x47, 0xf4, 0x10,
	0xba, 0x3f, 0x09, 0xd4, 0xcf, 0x33, 0xc6, 0x24, 0xcb, 0xf0, 0x2d, 0x34, 0x82, 0x70, 0xab, 0x64,
	0x58, 0x3a, 0x87, 0xee, 0xc3, 0xff, 0x64, 0xd2, 0x78, 0x6b, 0x57, 0xf0, 0x3d, 0x34, 0x0f, 0x7a,
	0x17, 0x1f, 0x97, 0x19, 0xb8, 0x77, 0x73, 0xf0, 0xca, 0x1d, 0xbc, 0x72, 0x87, 0xc1, 0x4b, 0x78,
	0xc2, 0x85, 0xb3, 0xca, 0xd2, 0x85, 0xc3, 0xbe, 0x85, 0x49, 0x1a, 0xb3, 0xfc, 0x88, 0x1d, 0xdc,
	0x57, 0xf0, 0xbc, 0x38, 0xcf, 0x8a, 0x9d, 0x99, 0x91, 0x5b, 0x5d, 0x2d, 0x8f, 0xf7, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0xcd, 0xaf, 0x6a, 0xac, 0x2e, 0x03, 0x00, 0x00,
}
