version: '3.3'
services:
  influxdb:
    container_name: influxdb
    #build:
    #  context: .
    image: influxdb
    ports:
      - 8086:8086
      - 8083:8083
    volumes:
      - /tmp/docker/influxdb/data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=demo
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=user
  #grafana:
   # image: grafana/grafana:latest
   # container_name: grafana
   # ports:
   #   - "3000:3000"
   # links:
   #   - influxdb
   # volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
   #   - /tmp/docker/grafana/data:/var/lib/grafana